export { default as DistributionMeta } from './DistributionMeta'
export { default as DistributionStats } from './DistributionStats'
export { default as GameAbout } from './GameAbout'
export { default as GameDetails } from './GameDetails'
export { default as GamePlatforms } from './GamePlatforms'
export { default as GameScreenshots } from './GameScreenshots'